base: &base
  adapter: postgresql
  encoding: utf8
  reconnect: true
  port: 5432
  pool: 50

development:
  <<: *base
  host: postgres
  database: sims
  username: postgres
  password: 'postgres'

test:
  <<: *base
  host: postgres
  database: sims_test
  username: postgres
  password: 'postgres'

production:
  <<: *base
  database: sims_prod
  # host: TODO
